# Generated by Django 4.0.5 on 2022-06-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0002_interiorimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interiorimage',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='interiorImage'),
        ),
    ]
