# Generated by Django 4.0.5 on 2022-06-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0003_alter_interiorimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorksOfMastersImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to='worksOfMastersImage')),
            ],
        ),
    ]
